/* soapClient.c
   Generated by gSOAP 2.8.138 for mobilecode.h

gSOAP XML Web services tools
Copyright (C) 2000-2025, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.138 2025-04-03 05:25:38 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getMobileCodeInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getMobileCodeInfo *ns1__getMobileCodeInfo, struct _ns1__getMobileCodeInfoResponse *ns1__getMobileCodeInfoResponse)
{	if (soap_send___ns1__getMobileCodeInfo(soap, soap_endpoint, soap_action, ns1__getMobileCodeInfo) || soap_recv___ns1__getMobileCodeInfo(soap, ns1__getMobileCodeInfoResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__getMobileCodeInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getMobileCodeInfo *ns1__getMobileCodeInfo)
{	struct __ns1__getMobileCodeInfo soap_tmp___ns1__getMobileCodeInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ws.webxml.com.cn/WebServices/MobileCodeWS.asmx";
	if (soap_action == NULL)
		soap_action = "http://WebXml.com.cn/getMobileCodeInfo";
	soap_tmp___ns1__getMobileCodeInfo.ns1__getMobileCodeInfo = ns1__getMobileCodeInfo;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__getMobileCodeInfo(soap, &soap_tmp___ns1__getMobileCodeInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getMobileCodeInfo(soap, &soap_tmp___ns1__getMobileCodeInfo, "-ns1:getMobileCodeInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getMobileCodeInfo(soap, &soap_tmp___ns1__getMobileCodeInfo, "-ns1:getMobileCodeInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__getMobileCodeInfo(struct soap *soap, struct _ns1__getMobileCodeInfoResponse *ns1__getMobileCodeInfoResponse)
{
	if (!ns1__getMobileCodeInfoResponse)
		return soap_closesock(soap);
	soap_default__ns1__getMobileCodeInfoResponse(soap, ns1__getMobileCodeInfoResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getMobileCodeInfoResponse(soap, ns1__getMobileCodeInfoResponse, "ns1:getMobileCodeInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getDatabaseInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getDatabaseInfo *ns1__getDatabaseInfo, struct _ns1__getDatabaseInfoResponse *ns1__getDatabaseInfoResponse)
{	if (soap_send___ns1__getDatabaseInfo(soap, soap_endpoint, soap_action, ns1__getDatabaseInfo) || soap_recv___ns1__getDatabaseInfo(soap, ns1__getDatabaseInfoResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__getDatabaseInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getDatabaseInfo *ns1__getDatabaseInfo)
{	struct __ns1__getDatabaseInfo soap_tmp___ns1__getDatabaseInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ws.webxml.com.cn/WebServices/MobileCodeWS.asmx";
	if (soap_action == NULL)
		soap_action = "http://WebXml.com.cn/getDatabaseInfo";
	soap_tmp___ns1__getDatabaseInfo.ns1__getDatabaseInfo = ns1__getDatabaseInfo;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__getDatabaseInfo(soap, &soap_tmp___ns1__getDatabaseInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getDatabaseInfo(soap, &soap_tmp___ns1__getDatabaseInfo, "-ns1:getDatabaseInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getDatabaseInfo(soap, &soap_tmp___ns1__getDatabaseInfo, "-ns1:getDatabaseInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__getDatabaseInfo(struct soap *soap, struct _ns1__getDatabaseInfoResponse *ns1__getDatabaseInfoResponse)
{
	if (!ns1__getDatabaseInfoResponse)
		return soap_closesock(soap);
	soap_default__ns1__getDatabaseInfoResponse(soap, ns1__getDatabaseInfoResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getDatabaseInfoResponse(soap, ns1__getDatabaseInfoResponse, "ns1:getDatabaseInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getMobileCodeInfo_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getMobileCodeInfo *ns1__getMobileCodeInfo, struct _ns1__getMobileCodeInfoResponse *ns1__getMobileCodeInfoResponse)
{	if (soap_send___ns1__getMobileCodeInfo_(soap, soap_endpoint, soap_action, ns1__getMobileCodeInfo) || soap_recv___ns1__getMobileCodeInfo_(soap, ns1__getMobileCodeInfoResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__getMobileCodeInfo_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getMobileCodeInfo *ns1__getMobileCodeInfo)
{	struct __ns1__getMobileCodeInfo_ soap_tmp___ns1__getMobileCodeInfo_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ws.webxml.com.cn/WebServices/MobileCodeWS.asmx";
	if (soap_action == NULL)
		soap_action = "http://WebXml.com.cn/getMobileCodeInfo";
	soap_tmp___ns1__getMobileCodeInfo_.ns1__getMobileCodeInfo = ns1__getMobileCodeInfo;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__getMobileCodeInfo_(soap, &soap_tmp___ns1__getMobileCodeInfo_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getMobileCodeInfo_(soap, &soap_tmp___ns1__getMobileCodeInfo_, "-ns1:getMobileCodeInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getMobileCodeInfo_(soap, &soap_tmp___ns1__getMobileCodeInfo_, "-ns1:getMobileCodeInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__getMobileCodeInfo_(struct soap *soap, struct _ns1__getMobileCodeInfoResponse *ns1__getMobileCodeInfoResponse)
{
	if (!ns1__getMobileCodeInfoResponse)
		return soap_closesock(soap);
	soap_default__ns1__getMobileCodeInfoResponse(soap, ns1__getMobileCodeInfoResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getMobileCodeInfoResponse(soap, ns1__getMobileCodeInfoResponse, "ns1:getMobileCodeInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getDatabaseInfo_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getDatabaseInfo *ns1__getDatabaseInfo, struct _ns1__getDatabaseInfoResponse *ns1__getDatabaseInfoResponse)
{	if (soap_send___ns1__getDatabaseInfo_(soap, soap_endpoint, soap_action, ns1__getDatabaseInfo) || soap_recv___ns1__getDatabaseInfo_(soap, ns1__getDatabaseInfoResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__getDatabaseInfo_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getDatabaseInfo *ns1__getDatabaseInfo)
{	struct __ns1__getDatabaseInfo_ soap_tmp___ns1__getDatabaseInfo_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ws.webxml.com.cn/WebServices/MobileCodeWS.asmx";
	if (soap_action == NULL)
		soap_action = "http://WebXml.com.cn/getDatabaseInfo";
	soap_tmp___ns1__getDatabaseInfo_.ns1__getDatabaseInfo = ns1__getDatabaseInfo;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__getDatabaseInfo_(soap, &soap_tmp___ns1__getDatabaseInfo_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getDatabaseInfo_(soap, &soap_tmp___ns1__getDatabaseInfo_, "-ns1:getDatabaseInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getDatabaseInfo_(soap, &soap_tmp___ns1__getDatabaseInfo_, "-ns1:getDatabaseInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__getDatabaseInfo_(struct soap *soap, struct _ns1__getDatabaseInfoResponse *ns1__getDatabaseInfoResponse)
{
	if (!ns1__getDatabaseInfoResponse)
		return soap_closesock(soap);
	soap_default__ns1__getDatabaseInfoResponse(soap, ns1__getDatabaseInfoResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getDatabaseInfoResponse(soap, ns1__getDatabaseInfoResponse, "ns1:getDatabaseInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
