/* soapStub.h
   Generated by gSOAP 2.8.138 for mobilecode.h

gSOAP XML Web services tools
Copyright (C) 2000-2025, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#define SOAP_NAMESPACE_OF_ns1	"http://WebXml.com.cn/"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 208138
# error "GSOAP VERSION 208138 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Structs and Unions                                                         *
 *                                                                            *
\******************************************************************************/

struct ns1__ArrayOfString;	/* mobilecode.h:176 */
struct _ns1__getMobileCodeInfo;	/* mobilecode.h:194 */
struct _ns1__getMobileCodeInfoResponse;	/* mobilecode.h:212 */
struct _ns1__getDatabaseInfo;	/* mobilecode.h:228 */
struct _ns1__getDatabaseInfoResponse;	/* mobilecode.h:242 */
struct __ns1__getMobileCodeInfo;	/* mobilecode.h:403 */
struct __ns1__getDatabaseInfo;	/* mobilecode.h:463 */
struct __ns1__getMobileCodeInfo_;	/* mobilecode.h:525 */
struct __ns1__getDatabaseInfo_;	/* mobilecode.h:585 */

/* mobilecode.h:176 */
#ifndef SOAP_TYPE_ns1__ArrayOfString
#define SOAP_TYPE_ns1__ArrayOfString (7)
/* complex XML schema type 'ns1:ArrayOfString': */
struct ns1__ArrayOfString {
        /** Sequence of elements 'ns1:string' of XML schema type 'xsd:string' stored in dynamic array string of length __sizestring */
        int __sizestring;
        char **string;
};
#endif

/* mobilecode.h:194 */
#ifndef SOAP_TYPE__ns1__getMobileCodeInfo
#define SOAP_TYPE__ns1__getMobileCodeInfo (9)
/* complex XML schema type 'ns1:getMobileCodeInfo': */
struct _ns1__getMobileCodeInfo {
        /** Optional element 'ns1:mobileCode' of XML schema type 'xsd:string' */
        char *mobileCode;
        /** Optional element 'ns1:userID' of XML schema type 'xsd:string' */
        char *userID;
};
#endif

/* mobilecode.h:212 */
#ifndef SOAP_TYPE__ns1__getMobileCodeInfoResponse
#define SOAP_TYPE__ns1__getMobileCodeInfoResponse (10)
/* complex XML schema type 'ns1:getMobileCodeInfoResponse': */
struct _ns1__getMobileCodeInfoResponse {
        /** Optional element 'ns1:getMobileCodeInfoResult' of XML schema type 'xsd:string' */
        char *getMobileCodeInfoResult;
};
#endif

/* mobilecode.h:228 */
#ifndef SOAP_TYPE__ns1__getDatabaseInfo
#define SOAP_TYPE__ns1__getDatabaseInfo (11)
/* complex XML schema type 'ns1:getDatabaseInfo': */
struct _ns1__getDatabaseInfo {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* mobilecode.h:242 */
#ifndef SOAP_TYPE__ns1__getDatabaseInfoResponse
#define SOAP_TYPE__ns1__getDatabaseInfoResponse (12)
/* complex XML schema type 'ns1:getDatabaseInfoResponse': */
struct _ns1__getDatabaseInfoResponse {
        /** Optional element 'ns1:getDatabaseInfoResult' of XML schema type 'ns1:ArrayOfString' */
        struct ns1__ArrayOfString *getDatabaseInfoResult;
};
#endif

/* mobilecode.h:403 */
#ifndef SOAP_TYPE___ns1__getMobileCodeInfo
#define SOAP_TYPE___ns1__getMobileCodeInfo (17)
/* Wrapper: */
struct __ns1__getMobileCodeInfo {
        /** Optional element 'ns1:getMobileCodeInfo' of XML schema type 'ns1:getMobileCodeInfo' */
        struct _ns1__getMobileCodeInfo *ns1__getMobileCodeInfo;
};
#endif

/* mobilecode.h:463 */
#ifndef SOAP_TYPE___ns1__getDatabaseInfo
#define SOAP_TYPE___ns1__getDatabaseInfo (21)
/* Wrapper: */
struct __ns1__getDatabaseInfo {
        /** Optional element 'ns1:getDatabaseInfo' of XML schema type 'ns1:getDatabaseInfo' */
        struct _ns1__getDatabaseInfo *ns1__getDatabaseInfo;
};
#endif

/* mobilecode.h:525 */
#ifndef SOAP_TYPE___ns1__getMobileCodeInfo_
#define SOAP_TYPE___ns1__getMobileCodeInfo_ (23)
/* Wrapper: */
struct __ns1__getMobileCodeInfo_ {
        /** Optional element 'ns1:getMobileCodeInfo' of XML schema type 'ns1:getMobileCodeInfo' */
        struct _ns1__getMobileCodeInfo *ns1__getMobileCodeInfo;
};
#endif

/* mobilecode.h:585 */
#ifndef SOAP_TYPE___ns1__getDatabaseInfo_
#define SOAP_TYPE___ns1__getDatabaseInfo_ (25)
/* Wrapper: */
struct __ns1__getDatabaseInfo_ {
        /** Optional element 'ns1:getDatabaseInfo' of XML schema type 'ns1:getDatabaseInfo' */
        struct _ns1__getDatabaseInfo *ns1__getDatabaseInfo;
};
#endif

/* mobilecode.h:710 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (26)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif
#endif

/* mobilecode.h:710 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (27)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
        /** Optional element 'SOAP-ENV:Value' of XML schema type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
};
#endif
#endif

/* mobilecode.h:710 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (29)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_<typename> assigned to __type */
        /** Do not create a cyclic data structure through this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
};
#endif
#endif

/* mobilecode.h:710 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (32)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
        /** Optional element 'SOAP-ENV:Text' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Text;
};
#endif
#endif

/* mobilecode.h:710 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (33)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
        /** Optional element 'faultcode' of XML schema type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XML schema type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XML schema type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XML schema type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (33)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (32)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (29)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (27)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (26)
#endif

/* struct _ns1__getDatabaseInfoResponse has binding name '_ns1__getDatabaseInfoResponse' for type '' */
#ifndef SOAP_TYPE__ns1__getDatabaseInfoResponse
#define SOAP_TYPE__ns1__getDatabaseInfoResponse (12)
#endif

/* struct _ns1__getDatabaseInfo has binding name '_ns1__getDatabaseInfo' for type '' */
#ifndef SOAP_TYPE__ns1__getDatabaseInfo
#define SOAP_TYPE__ns1__getDatabaseInfo (11)
#endif

/* struct _ns1__getMobileCodeInfoResponse has binding name '_ns1__getMobileCodeInfoResponse' for type '' */
#ifndef SOAP_TYPE__ns1__getMobileCodeInfoResponse
#define SOAP_TYPE__ns1__getMobileCodeInfoResponse (10)
#endif

/* struct _ns1__getMobileCodeInfo has binding name '_ns1__getMobileCodeInfo' for type '' */
#ifndef SOAP_TYPE__ns1__getMobileCodeInfo
#define SOAP_TYPE__ns1__getMobileCodeInfo (9)
#endif

/* struct ns1__ArrayOfString has binding name 'ns1__ArrayOfString' for type 'ns1:ArrayOfString' */
#ifndef SOAP_TYPE_ns1__ArrayOfString
#define SOAP_TYPE_ns1__ArrayOfString (7)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (35)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (34)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (28)
#endif

/* struct _ns1__getDatabaseInfoResponse * has binding name 'PointerTo_ns1__getDatabaseInfoResponse' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__getDatabaseInfoResponse
#define SOAP_TYPE_PointerTo_ns1__getDatabaseInfoResponse (19)
#endif

/* struct _ns1__getDatabaseInfo * has binding name 'PointerTo_ns1__getDatabaseInfo' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__getDatabaseInfo
#define SOAP_TYPE_PointerTo_ns1__getDatabaseInfo (18)
#endif

/* struct _ns1__getMobileCodeInfoResponse * has binding name 'PointerTo_ns1__getMobileCodeInfoResponse' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__getMobileCodeInfoResponse
#define SOAP_TYPE_PointerTo_ns1__getMobileCodeInfoResponse (15)
#endif

/* struct _ns1__getMobileCodeInfo * has binding name 'PointerTo_ns1__getMobileCodeInfo' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__getMobileCodeInfo
#define SOAP_TYPE_PointerTo_ns1__getMobileCodeInfo (14)
#endif

/* struct ns1__ArrayOfString * has binding name 'PointerTons1__ArrayOfString' for type 'ns1:ArrayOfString' */
#ifndef SOAP_TYPE_PointerTons1__ArrayOfString
#define SOAP_TYPE_PointerTons1__ArrayOfString (13)
#endif

/* char ** has binding name 'PointerTostring' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (8)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    
    /** Web service synchronous operation 'soap_call___ns1__getMobileCodeInfo' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getMobileCodeInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getMobileCodeInfo *ns1__getMobileCodeInfo, struct _ns1__getMobileCodeInfoResponse *ns1__getMobileCodeInfoResponse);
    /** Web service asynchronous operation 'soap_send___ns1__getMobileCodeInfo' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__getMobileCodeInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getMobileCodeInfo *ns1__getMobileCodeInfo);
    /** Web service asynchronous operation 'soap_recv___ns1__getMobileCodeInfo' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__getMobileCodeInfo(struct soap *soap, struct _ns1__getMobileCodeInfoResponse *ns1__getMobileCodeInfoResponse);
    
    /** Web service synchronous operation 'soap_call___ns1__getDatabaseInfo' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getDatabaseInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getDatabaseInfo *ns1__getDatabaseInfo, struct _ns1__getDatabaseInfoResponse *ns1__getDatabaseInfoResponse);
    /** Web service asynchronous operation 'soap_send___ns1__getDatabaseInfo' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__getDatabaseInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getDatabaseInfo *ns1__getDatabaseInfo);
    /** Web service asynchronous operation 'soap_recv___ns1__getDatabaseInfo' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__getDatabaseInfo(struct soap *soap, struct _ns1__getDatabaseInfoResponse *ns1__getDatabaseInfoResponse);
    
    /** Web service synchronous operation 'soap_call___ns1__getMobileCodeInfo_' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getMobileCodeInfo_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getMobileCodeInfo *ns1__getMobileCodeInfo, struct _ns1__getMobileCodeInfoResponse *ns1__getMobileCodeInfoResponse);
    /** Web service asynchronous operation 'soap_send___ns1__getMobileCodeInfo_' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__getMobileCodeInfo_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getMobileCodeInfo *ns1__getMobileCodeInfo);
    /** Web service asynchronous operation 'soap_recv___ns1__getMobileCodeInfo_' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__getMobileCodeInfo_(struct soap *soap, struct _ns1__getMobileCodeInfoResponse *ns1__getMobileCodeInfoResponse);
    
    /** Web service synchronous operation 'soap_call___ns1__getDatabaseInfo_' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getDatabaseInfo_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getDatabaseInfo *ns1__getDatabaseInfo, struct _ns1__getDatabaseInfoResponse *ns1__getDatabaseInfoResponse);
    /** Web service asynchronous operation 'soap_send___ns1__getDatabaseInfo_' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__getDatabaseInfo_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getDatabaseInfo *ns1__getDatabaseInfo);
    /** Web service asynchronous operation 'soap_recv___ns1__getDatabaseInfo_' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__getDatabaseInfo_(struct soap *soap, struct _ns1__getDatabaseInfoResponse *ns1__getDatabaseInfoResponse);

#endif

/* End of soapStub.h */
